Do not recalculate bounds if provided
gl-vis/snap-points-2d pull request #1
Opened 2017-07-27 13:02 UTC by dfcreative

If we want to calc snapping on a subset of some larger data, we may want to provide actual bounds rather than calculate it.
Also [array-bounds](https://github.com/dfcreative/array-bounds) turns out to be a bit faster.

2017-08-25 11:08 UTC, monfera commented
Is it possible to lock in the improvement with added testing?

2017-08-25 12:22 UTC, dfcreative commented
@monfera you mean to add test of the added feature?

2017-08-25 12:28 UTC, monfera commented
@dfcreative yes, I'm not sure though if the nature of the change makes it straightforward enough though.

2017-08-25 12:53 UTC, monfera requested changes
All points disappear in `gl-vis/gl-scatter2d` when the dependency is changed to:
```
    "snap-points-2d": "gl-vis/snap-points-2d#optimize", // == commit dabba37
```

![image](https://user-images.githubusercontent.com/1548516/29714619-496f842e-89a4-11e7-85e0-76a4f82c68e3.png)

I busted `node_modules`, `npm i` and restarted `budo example/points.js --open --live` when switching back & forth. Might be something shallow, is it what you see too?

2017-08-25 15:13 UTC, monfera commented
As this PR is a perf opt for splatting, this may be pertinent (just bouncing off the idea for now): https://github.com/gl-vis/gl-scatter2d/issues/8#issuecomment-324949556

2017-08-25 20:50 UTC, dfcreative commented
@monfera https://github.com/gl-vis/snap-points-2d/pull/1/commits/51cf52fd260ad4de4afd316f9fa859bf3bb8ea2e fixed extended bounds test case and gl-scatter2d case, thanks for the check!

2017-08-25 21:45 UTC, monfera commented
@dfcreative looks great, thanks! I'll continue w/ the code.

2017-08-28 11:38 UTC, monfera reviewed
Thanks for the added commits, works nice, added some code related questions.

2017-08-28 11:38 UTC, monfera commented on package.json
> -  },
Are we losing anything by phasing out `typedarray-pool`? What did it bring in that may be worth preserving?

2017-08-28 11:38 UTC, monfera commented on snap.js
not sure if it was Plotly work or not, @etpinard should modules like `array-bounds` go under `gl-vis` / `plotly` or it doesn't matter? Also, didn't immediately see copyright/license, what should be our guide?

Also, I suppose `array-bounds` should also be reviewed, ie. somehow making a PR out of it, or not? (I see this dependency is merged in `gl-scatter2d`)

2017-08-28 11:38 UTC, monfera commented on snap.js
> +    var b = getBounds(points, 2)
How do conditions such as `bounds[0] >= bounds[2]` arise? Is it safe to assume that if `bounds[0] < bounds[2]` then it will _not_ require recalc with `getBounds()`?

2017-08-28 11:38 UTC, monfera commented on snap.js
> +
I assume it is guaranteed that if some elements of `bounds` are populated, then all are populated (e.g. there.s a `bounds.length` check that returns `true` even with one element). If this is the case, maybe an uninitialized `bounds` could simply be `null` or `[NaN, NaN, NaN, NaN]` or would it just complicate the code?

2017-08-28 11:38 UTC, monfera commented on snap.js
> +}
these functions are unchanged, would be useful to leave them where they were (easier `diff`, intact `git blame`, other functions eg. `snapPoints ` live on top of the file)

2017-08-28 11:38 UTC, monfera commented on test/test.js
> +})
Thanks for adding these tests!

2017-08-28 11:38 UTC, monfera commented on test/test.js
> +})
It seems like some preexisting tests are a bit stochastic, often, all tests pass, but sometimes, one or a few tests fail, eg. 
```
not ok 169 45:0.10685386291411322,0.9691737880693028 is not covered - closest pt = 0.9691737880693028
  ---
    operator: ok
    expected: true
    actual:   false
    at: verifySnap (/Users/robert/repos/gl-vis/snap-points-2d/test/test.js:61:11)
  ...

not ok 182 32:0.12461741880331921,0.9867125665658801 is not covered - closest pt = 0.9867125665658801
  ---
    operator: ok
    expected: true
    actual:   false
    at: verifySnap (/Users/robert/repos/gl-vis/snap-points-2d/test/test.js:61:11)
  ...

not ok 197 17:0.5195915786361036,1 is not covered - closest pt = 1
  ---
    operator: ok
    expected: true
    actual:   false
    at: verifySnap (/Users/robert/repos/gl-vis/snap-points-2d/test/test.js:61:11)
  ...

1..305
# tests 305
# pass  302
# fail  3
```

I'm not sure if we want to look into it in this PR or circle back to it, maybe worth a quick check (@etpinard ?). At least it'd be good to know if these test cases sometimes failed before the PR commits ie. if this is independent.

2017-08-28 12:45 UTC, dfcreative commented on package.json
> -  },
@monfera it's a question of garbage collector vs manual control + garbage collector. The second case seems unnecessary complication here - gc anyways cleans up freed reference.

2017-08-28 12:48 UTC, dfcreative commented on snap.js
> +
Strictly speaking it is possible to enhance detection. The premise is we need only reference to some holder array to fill with found boundaries, and if it already contains valid bounds, then we assume we don't have to recalculate them.

2017-08-28 12:59 UTC, dfcreative commented on snap.js
> +    var b = getBounds(points, 2)
The condition arises from usual init values of limits, eg. `min = 1e9, max = -19e` etc.
As for assumption - we can't think too much for the user, we expect if passed bounds are valid then we use them - and we should not guess anything else, following Occam's razor principle. And why should not we?

2017-08-28 13:03 UTC, dfcreative commented on snap.js
> +}
Well I believe git is created to deal with changes, not to block them. From readability perspective it is easier to see main things and secondary functions like `partition` after, explaining the main part (there are articles on that).

2017-08-28 13:06 UTC, dfcreative commented on test/test.js
> +})
@monfera they failed before too, I decided not to dig and leave it as is.

2017-08-28 13:16 UTC, dfcreative commented on snap.js
Sure: https://github.com/dfcreative/array-bounds/blob/master/index.js

2017-08-28 13:27 UTC, monfera commented on snap.js
> +}
thats the theory though here git is lost 😸  it shows uncompared adds/deletes and no longer shows Mikola. Btw. it's cool if we change standards, it used to be functions on top.

2017-08-28 13:27 UTC, monfera commented on test/test.js
> +})
Thanks for checking!

2017-08-28 13:40 UTC, dfcreative commented on snap.js
> +}
@monfera if that is a change of standard, I can unroll the change. Readability in this case is less important.

2017-08-28 13:42 UTC, monfera commented on snap.js
code & tests look great!

2017-08-28 13:56 UTC, etpinard commented on snap.js
@etpinard should modules like array-bounds go under gl-vis / plotly or it doesn't matter?

does not matter.

2017-08-28 14:04 UTC, monfera commented on snap.js
> +}
Étienne said it's not standardized, for new files we can put it in whatever order. I saw you switched back, helps `git bisect` or other rare occasion a `diff` is needed.

2017-08-28 14:04 UTC, monfera approved these changes

2017-08-28 14:05 UTC, monfera commented
nice work! 💃

2017-08-28 18:13 UTC, merged